services:
  server:
    build:
      context: .
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://inangara:pass@db:5432/prod_real_estate_db

  db:
    image: postgres:15-alpine
    restart: always
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=prod_real_estate_db
      - POSTGRES_USER=inangara
      - POSTGRES_PASSWORD=pass
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "inangara", "-d", "prod_real_estate_db" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:
