"""Add role-specific profile tables for hybrid role system

Revision ID: 0b2ed626d8af
Revises: 457818c8d86d
Create Date: 2025-10-25 02:03:39.497054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b2ed626d8af'
down_revision: Union[str, None] = '457818c8d86d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('license_number', sa.String(length=100), nullable=False),
    sa.Column('license_state', sa.String(length=50), nullable=False),
    sa.Column('license_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('license_type', sa.String(length=50), nullable=True),
    sa.Column('agency_name', sa.String(length=200), nullable=True),
    sa.Column('agency_license', sa.String(length=100), nullable=True),
    sa.Column('agency_phone', sa.String(length=20), nullable=True),
    sa.Column('agency_address', sa.Text(), nullable=True),
    sa.Column('broker_name', sa.String(length=100), nullable=True),
    sa.Column('broker_license', sa.String(length=100), nullable=True),
    sa.Column('years_experience', sa.Integer(), nullable=True),
    sa.Column('specializations', sa.JSON(), nullable=True),
    sa.Column('service_areas', sa.JSON(), nullable=True),
    sa.Column('languages_spoken', sa.JSON(), nullable=True),
    sa.Column('total_sales', sa.Integer(), nullable=True),
    sa.Column('total_volume', sa.Float(), nullable=True),
    sa.Column('average_sale_price', sa.Float(), nullable=True),
    sa.Column('client_satisfaction_rating', sa.Float(), nullable=True),
    sa.Column('response_time_hours', sa.Float(), nullable=True),
    sa.Column('certifications', sa.JSON(), nullable=True),
    sa.Column('awards', sa.JSON(), nullable=True),
    sa.Column('professional_memberships', sa.JSON(), nullable=True),
    sa.Column('office_phone', sa.String(length=20), nullable=True),
    sa.Column('mobile_phone', sa.String(length=20), nullable=True),
    sa.Column('website', sa.String(length=200), nullable=True),
    sa.Column('linkedin_profile', sa.String(length=200), nullable=True),
    sa.Column('availability_hours', sa.Text(), nullable=True),
    sa.Column('commission_rate', sa.Float(), nullable=True),
    sa.Column('minimum_commission', sa.Float(), nullable=True),
    sa.Column('fee_structure', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('verification_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('background_check_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('insurance_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('license_number'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_agent_profiles_id'), 'agent_profiles', ['id'], unique=False)
    op.create_table('investor_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('investment_experience', sa.String(length=50), nullable=True),
    sa.Column('investment_focus', sa.JSON(), nullable=True),
    sa.Column('investment_strategy', sa.JSON(), nullable=True),
    sa.Column('total_investment_capital', sa.Float(), nullable=True),
    sa.Column('available_capital', sa.Float(), nullable=True),
    sa.Column('annual_income', sa.Float(), nullable=True),
    sa.Column('net_worth', sa.Float(), nullable=True),
    sa.Column('credit_score', sa.Integer(), nullable=True),
    sa.Column('total_properties_owned', sa.Integer(), nullable=True),
    sa.Column('total_properties_managed', sa.Integer(), nullable=True),
    sa.Column('portfolio_value', sa.Float(), nullable=True),
    sa.Column('annual_roi', sa.Float(), nullable=True),
    sa.Column('properties_owned', sa.JSON(), nullable=True),
    sa.Column('preferred_property_types', sa.JSON(), nullable=True),
    sa.Column('preferred_locations', sa.JSON(), nullable=True),
    sa.Column('budget_range_min', sa.Float(), nullable=True),
    sa.Column('budget_range_max', sa.Float(), nullable=True),
    sa.Column('preferred_deal_size', sa.String(length=50), nullable=True),
    sa.Column('risk_tolerance', sa.String(length=50), nullable=True),
    sa.Column('investment_timeline', sa.String(length=50), nullable=True),
    sa.Column('liquidity_needs', sa.String(length=50), nullable=True),
    sa.Column('company_name', sa.String(length=200), nullable=True),
    sa.Column('job_title', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('years_in_industry', sa.Integer(), nullable=True),
    sa.Column('first_investment_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_investments_made', sa.Integer(), nullable=True),
    sa.Column('successful_deals', sa.Integer(), nullable=True),
    sa.Column('failed_deals', sa.Integer(), nullable=True),
    sa.Column('average_deal_size', sa.Float(), nullable=True),
    sa.Column('investment_partners', sa.JSON(), nullable=True),
    sa.Column('preferred_partnership_types', sa.JSON(), nullable=True),
    sa.Column('networking_events_attended', sa.Integer(), nullable=True),
    sa.Column('investment_goals', sa.Text(), nullable=True),
    sa.Column('target_roi', sa.Float(), nullable=True),
    sa.Column('target_cash_flow', sa.Float(), nullable=True),
    sa.Column('exit_strategy_preferences', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('verification_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accreditation_status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_investor_profiles_id'), 'investor_profiles', ['id'], unique=False)
    op.create_table('landlord_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('business_name', sa.String(length=200), nullable=True),
    sa.Column('business_type', sa.String(length=50), nullable=True),
    sa.Column('tax_id', sa.String(length=50), nullable=True),
    sa.Column('business_license', sa.String(length=100), nullable=True),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.Column('bank_routing_number', sa.String(length=20), nullable=True),
    sa.Column('bank_account_number', sa.String(length=50), nullable=True),
    sa.Column('bank_account_type', sa.String(length=50), nullable=True),
    sa.Column('total_properties', sa.Integer(), nullable=True),
    sa.Column('total_units', sa.Integer(), nullable=True),
    sa.Column('properties_managed', sa.JSON(), nullable=True),
    sa.Column('management_company', sa.String(length=200), nullable=True),
    sa.Column('property_manager_name', sa.String(length=100), nullable=True),
    sa.Column('property_manager_phone', sa.String(length=20), nullable=True),
    sa.Column('annual_rental_income', sa.Float(), nullable=True),
    sa.Column('monthly_rental_income', sa.Float(), nullable=True),
    sa.Column('property_valuation', sa.Float(), nullable=True),
    sa.Column('mortgage_balance', sa.Float(), nullable=True),
    sa.Column('insurance_company', sa.String(length=200), nullable=True),
    sa.Column('insurance_policy_number', sa.String(length=100), nullable=True),
    sa.Column('insurance_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('legal_entity_type', sa.String(length=50), nullable=True),
    sa.Column('preferred_lease_terms', sa.Text(), nullable=True),
    sa.Column('pet_policy', sa.Text(), nullable=True),
    sa.Column('smoking_policy', sa.Text(), nullable=True),
    sa.Column('maintenance_preferences', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('verification_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_landlord_profiles_id'), 'landlord_profiles', ['id'], unique=False)
    op.create_table('tenant_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('employment_status', sa.String(length=50), nullable=True),
    sa.Column('employer_name', sa.String(length=200), nullable=True),
    sa.Column('job_title', sa.String(length=100), nullable=True),
    sa.Column('annual_income', sa.Float(), nullable=True),
    sa.Column('monthly_income', sa.Float(), nullable=True),
    sa.Column('income_verification_documents', sa.Text(), nullable=True),
    sa.Column('credit_score', sa.Integer(), nullable=True),
    sa.Column('credit_score_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.Column('bank_account_type', sa.String(length=50), nullable=True),
    sa.Column('previous_landlord_name', sa.String(length=200), nullable=True),
    sa.Column('previous_landlord_phone', sa.String(length=20), nullable=True),
    sa.Column('previous_rent_amount', sa.Float(), nullable=True),
    sa.Column('rental_history_years', sa.Float(), nullable=True),
    sa.Column('eviction_history', sa.Boolean(), nullable=True),
    sa.Column('references', sa.Text(), nullable=True),
    sa.Column('preferred_lease_duration', sa.Integer(), nullable=True),
    sa.Column('pet_owner', sa.Boolean(), nullable=True),
    sa.Column('smoking', sa.Boolean(), nullable=True),
    sa.Column('max_rent_budget', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_tenant_profiles_id'), 'tenant_profiles', ['id'], unique=False)
    # Add roles column as nullable first, then update existing users, then make it NOT NULL
    op.add_column('users', sa.Column('roles', sa.JSON(), nullable=True))
    
    # Update existing users to have empty roles array
    op.execute("UPDATE users SET roles = '[]'::json WHERE roles IS NULL")
    
    # Now make it NOT NULL
    op.alter_column('users', 'roles', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'roles')
    op.drop_index(op.f('ix_tenant_profiles_id'), table_name='tenant_profiles')
    op.drop_table('tenant_profiles')
    op.drop_index(op.f('ix_landlord_profiles_id'), table_name='landlord_profiles')
    op.drop_table('landlord_profiles')
    op.drop_index(op.f('ix_investor_profiles_id'), table_name='investor_profiles')
    op.drop_table('investor_profiles')
    op.drop_index(op.f('ix_agent_profiles_id'), table_name='agent_profiles')
    op.drop_table('agent_profiles')
    # ### end Alembic commands ###
