"""add_listing_type_column_to_properties

Revision ID: 1b8adb9dd7ba
Revises: 91251010ccd5
Create Date: 2025-11-07 22:38:40.159634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b8adb9dd7ba'
down_revision: Union[str, None] = '91251010ccd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create enum type with lowercase values to match Python enum
    listing_type_enum = sa.Enum('for_sale', 'for_rent', 'for_lease', 'for_auction', name='listingtype')
    listing_type_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('properties', sa.Column('listing_type', listing_type_enum, nullable=True))
    op.create_index(op.f('ix_properties_listing_type'), 'properties', ['listing_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop index if it exists (handles case where index was never created or already dropped)
    from sqlalchemy import inspect
    bind = op.get_bind()
    inspector = inspect(bind)
    indexes = [idx['name'] for idx in inspector.get_indexes('properties')]
    if 'ix_properties_listing_type' in indexes:
        op.drop_index(op.f('ix_properties_listing_type'), table_name='properties')
    
    # Drop column if it exists
    columns = [col['name'] for col in inspector.get_columns('properties')]
    if 'listing_type' in columns:
        op.drop_column('properties', 'listing_type')
    # ### end Alembic commands ###
