"""Remove JSON roles column from User model

Revision ID: 457818c8d86d
Revises: 0eda37107248
Create Date: 2025-10-25 01:29:54.007677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '457818c8d86d'
down_revision: Union[str, None] = '0eda37107248'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sellers_id', table_name='sellers')
    op.drop_table('sellers')
    op.alter_column('applications', 'status',
               existing_type=postgresql.ENUM('PENDING', 'APPROVED', 'REJECTED', 'WITHDRAWN', 'UNDER_REVIEW', name='applicationstatus'),
               type_=sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'WITHDRAWN', 'UNDER_REVIEW', name='applicationstatus', native_enum=False),
               nullable=False)
    op.alter_column('applications', 'move_in_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    # Convert TEXT to JSON with proper casting
    op.execute("ALTER TABLE applications ALTER COLUMN documents_urls TYPE JSON USING documents_urls::json")
    op.alter_column('applications', 'documents_urls',
               existing_type=sa.JSON(),
               nullable=False)
    op.alter_column('applications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # Update NULL values in updated_at before making it NOT NULL
    op.execute("UPDATE applications SET updated_at = created_at WHERE updated_at IS NULL")
    op.alter_column('applications', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.create_index(op.f('ix_applications_applicant_id'), 'applications', ['applicant_id'], unique=False)
    op.create_index(op.f('ix_applications_is_active'), 'applications', ['is_active'], unique=False)
    op.create_index(op.f('ix_applications_property_id'), 'applications', ['property_id'], unique=False)
    op.alter_column('favorites', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_favorites_property_id'), 'favorites', ['property_id'], unique=False)
    op.create_index(op.f('ix_favorites_user_id'), 'favorites', ['user_id'], unique=False)
    op.drop_column('users', 'roles')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('roles', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_favorites_user_id'), table_name='favorites')
    op.drop_index(op.f('ix_favorites_property_id'), table_name='favorites')
    op.alter_column('favorites', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_applications_property_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_is_active'), table_name='applications')
    op.drop_index(op.f('ix_applications_applicant_id'), table_name='applications')
    op.alter_column('applications', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('applications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('applications', 'documents_urls',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('applications', 'move_in_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('applications', 'status',
               existing_type=sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'WITHDRAWN', 'UNDER_REVIEW', name='applicationstatus', native_enum=False),
               type_=postgresql.ENUM('PENDING', 'APPROVED', 'REJECTED', 'WITHDRAWN', 'UNDER_REVIEW', name='applicationstatus'),
               nullable=True)
    op.create_table('sellers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_old', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='sellers_pkey')
    )
    op.create_index('ix_sellers_id', 'sellers', ['id'], unique=False)
    # ### end Alembic commands ###
