"""add_maintenance_staff_profile

Revision ID: 49b85c620859
Revises: 4d0ec2b7343b
Create Date: 2025-11-27 12:22:55.696402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49b85c620859'
down_revision: Union[str, None] = '4d0ec2b7343b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maintenance_staff_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('skills', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # Create indexes from __table_args__ (explicit indexes)
    op.create_index('ix_maintenance_staff_profile_user_id', 'maintenance_staff_profiles', ['user_id'], unique=False)
    op.create_index('ix_maintenance_staff_profile_is_active', 'maintenance_staff_profiles', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_maintenance_staff_profile_is_active', table_name='maintenance_staff_profiles')
    op.drop_index('ix_maintenance_staff_profile_user_id', table_name='maintenance_staff_profiles')
    op.drop_table('maintenance_staff_profiles')
    # ### end Alembic commands ###
