"""create maintenance table

Revision ID: 4d0ec2b7343b
Revises: dac521e361af
Create Date: 2025-11-26 15:14:50.260669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d0ec2b7343b'
down_revision: Union[str, None] = 'dac521e361af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maintenance_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('unit_number', sa.String(length=50), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('reported_by_id', sa.Integer(), nullable=False),
    sa.Column('assigned_staff_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'EMERGENCY', name='maintenancepriority', native_enum=False), nullable=False),
    sa.Column('category', sa.Enum('PLUMBING', 'ELECTRICAL', 'HVAC', 'APPLIANCE', 'STRUCTURAL', 'PEST_CONTROL', 'CLEANING', 'GENERAL', 'OTHER', name='maintenancecategory', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('REPORTED', 'REVIEWING', 'ASSIGNED', 'ACKNOWLEDGED', 'IN_PROGRESS', 'COMPLETED', 'VERIFIED', 'CLOSED', 'REJECTED', 'CANCELLED', 'REOPENED', name='maintenancestatus', native_enum=False), nullable=False),
    sa.Column('estimated_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('actual_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('cost_approved_by_id', sa.Integer(), nullable=True),
    sa.Column('external_vendor_name', sa.String(length=255), nullable=True),
    sa.Column('external_vendor_contact', sa.String(length=255), nullable=True),
    sa.Column('access_instructions', sa.Text(), nullable=True),
    sa.Column('preferred_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('preferred_time', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_status_change', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_staff_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['cost_approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reported_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # Explicit indexes from __table_args__
    op.create_index('ix_maintenance_request_assigned_staff_id', 'maintenance_requests', ['assigned_staff_id'], unique=False)
    op.create_index('ix_maintenance_request_created_at', 'maintenance_requests', ['created_at'], unique=False)
    op.create_index('ix_maintenance_request_is_active', 'maintenance_requests', ['is_active'], unique=False)
    op.create_index('ix_maintenance_request_priority', 'maintenance_requests', ['priority'], unique=False)
    op.create_index('ix_maintenance_request_property_id', 'maintenance_requests', ['property_id'], unique=False)
    op.create_index('ix_maintenance_request_status', 'maintenance_requests', ['status'], unique=False)
    op.create_index('ix_maintenance_request_tenant_id', 'maintenance_requests', ['tenant_id'], unique=False)
    # Additional auto-generated indexes (not in __table_args__)
    op.create_index(op.f('ix_maintenance_requests_id'), 'maintenance_requests', ['id'], unique=False)
    op.create_index(op.f('ix_maintenance_requests_reported_by_id'), 'maintenance_requests', ['reported_by_id'], unique=False)
    op.create_table('maintenance_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('action_data', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['maintenance_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # Explicit indexes from __table_args__
    op.create_index('ix_maintenance_activity_action_type', 'maintenance_activities', ['action_type'], unique=False)
    op.create_index('ix_maintenance_activity_created_at', 'maintenance_activities', ['created_at'], unique=False)
    op.create_index('ix_maintenance_activity_request_id', 'maintenance_activities', ['request_id'], unique=False)
    # Additional auto-generated indexes (not in __table_args__)
    op.create_index(op.f('ix_maintenance_activities_id'), 'maintenance_activities', ['id'], unique=False)
    op.create_index(op.f('ix_maintenance_activities_actor_id'), 'maintenance_activities', ['actor_id'], unique=False)
    op.create_table('maintenance_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['maintenance_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # Explicit indexes from __table_args__
    op.create_index('ix_maintenance_attachment_request_id', 'maintenance_attachments', ['request_id'], unique=False)
    op.create_index('ix_maintenance_attachment_uploaded_at', 'maintenance_attachments', ['uploaded_at'], unique=False)
    # Additional auto-generated indexes (not in __table_args__)
    op.create_index(op.f('ix_maintenance_attachments_id'), 'maintenance_attachments', ['id'], unique=False)
    op.create_index(op.f('ix_maintenance_attachments_uploaded_by_id'), 'maintenance_attachments', ['uploaded_by_id'], unique=False)
    op.create_table('maintenance_status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('changed_by_id', sa.Integer(), nullable=False),
    sa.Column('old_status', sa.String(length=30), nullable=True),
    sa.Column('new_status', sa.String(length=30), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['maintenance_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # Explicit indexes from __table_args__
    op.create_index('ix_maintenance_status_history_changed_at', 'maintenance_status_history', ['changed_at'], unique=False)
    op.create_index('ix_maintenance_status_history_request_id', 'maintenance_status_history', ['request_id'], unique=False)
    # Additional auto-generated indexes (not in __table_args__)
    op.create_index(op.f('ix_maintenance_status_history_id'), 'maintenance_status_history', ['id'], unique=False)
    op.create_index(op.f('ix_maintenance_status_history_changed_by_id'), 'maintenance_status_history', ['changed_by_id'], unique=False)
    op.alter_column('leases', 'application_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('leases', 'application_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # Drop explicit indexes from __table_args__
    op.drop_index('ix_maintenance_status_history_changed_at', table_name='maintenance_status_history')
    op.drop_index('ix_maintenance_status_history_request_id', table_name='maintenance_status_history')
    # Drop additional auto-generated indexes
    op.drop_index(op.f('ix_maintenance_status_history_id'), table_name='maintenance_status_history')
    op.drop_index(op.f('ix_maintenance_status_history_changed_by_id'), table_name='maintenance_status_history')
    op.drop_table('maintenance_status_history')
    # Drop explicit indexes from __table_args__
    op.drop_index('ix_maintenance_attachment_request_id', table_name='maintenance_attachments')
    op.drop_index('ix_maintenance_attachment_uploaded_at', table_name='maintenance_attachments')
    # Drop additional auto-generated indexes
    op.drop_index(op.f('ix_maintenance_attachments_id'), table_name='maintenance_attachments')
    op.drop_index(op.f('ix_maintenance_attachments_uploaded_by_id'), table_name='maintenance_attachments')
    op.drop_table('maintenance_attachments')
    # Drop explicit indexes from __table_args__
    op.drop_index('ix_maintenance_activity_action_type', table_name='maintenance_activities')
    op.drop_index('ix_maintenance_activity_created_at', table_name='maintenance_activities')
    op.drop_index('ix_maintenance_activity_request_id', table_name='maintenance_activities')
    # Drop additional auto-generated indexes
    op.drop_index(op.f('ix_maintenance_activities_id'), table_name='maintenance_activities')
    op.drop_index(op.f('ix_maintenance_activities_actor_id'), table_name='maintenance_activities')
    op.drop_table('maintenance_activities')
    # Drop explicit indexes from __table_args__
    op.drop_index('ix_maintenance_request_assigned_staff_id', table_name='maintenance_requests')
    op.drop_index('ix_maintenance_request_created_at', table_name='maintenance_requests')
    op.drop_index('ix_maintenance_request_is_active', table_name='maintenance_requests')
    op.drop_index('ix_maintenance_request_priority', table_name='maintenance_requests')
    op.drop_index('ix_maintenance_request_property_id', table_name='maintenance_requests')
    op.drop_index('ix_maintenance_request_status', table_name='maintenance_requests')
    op.drop_index('ix_maintenance_request_tenant_id', table_name='maintenance_requests')
    # Drop additional auto-generated indexes
    op.drop_index(op.f('ix_maintenance_requests_id'), table_name='maintenance_requests')
    op.drop_index(op.f('ix_maintenance_requests_reported_by_id'), table_name='maintenance_requests')
    op.drop_table('maintenance_requests')
    # ### end Alembic commands ###
