"""add_refresh_tokens_table

Revision ID: 91251010ccd5
Revises: 6b12059d95c8
Create Date: 2025-11-05 18:29:48.056242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '91251010ccd5'
down_revision: Union[str, None] = '6b12059d95c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: refresh_tokens table already exists (created by Base.metadata.create_all)
    # This migration is kept for documentation but does not create the table
    # The table was created automatically when the app started
    
    # IMPORTANT: Do not remove indexes or change JSONB to JSON
    # The database has JSONB with indexes for performance - keep them!
    # The model uses JSON for cross-database compatibility, but PostgreSQL uses JSONB
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: refresh_tokens table exists but was created by Base.metadata.create_all
    # If you need to remove it, use: op.drop_table('refresh_tokens')
    # But this is not recommended as it will break active user sessions
    pass
    # ### end Alembic commands ###
