"""add_references_and_consent_to_applications

Revision ID: 9c065c1a64ea
Revises: 7a30e2f1513a
Create Date: 2025-11-20 16:35:22.169761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c065c1a64ea'
down_revision: Union[str, None] = '7a30e2f1513a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('references', sa.JSON(), nullable=True))
    # Add column with default value first, then update existing rows, then make it NOT NULL
    op.add_column('applications', sa.Column('background_check_consent', sa.Boolean(), nullable=True, server_default=sa.text('false')))
    # Update existing rows to have default value (safety check, though server_default handles it)
    op.execute("UPDATE applications SET background_check_consent = false WHERE background_check_consent IS NULL")
    # Now make it NOT NULL and remove server_default (model handles default in Python)
    op.alter_column('applications', 'background_check_consent', nullable=False, server_default=None)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.drop_constraint('uq_documents_file_id', 'documents', type_='unique')
    op.create_index(op.f('ix_documents_file_id'), 'documents', ['file_id'], unique=True)
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.drop_constraint('kyc_requests_provider_reference_key', 'kyc_requests', type_='unique')
    op.drop_index('ix_kyc_requests_provider_reference', table_name='kyc_requests')
    op.create_index(op.f('ix_kyc_requests_provider_reference'), 'kyc_requests', ['provider_reference'], unique=True)
    op.create_index(op.f('ix_kyc_requests_id'), 'kyc_requests', ['id'], unique=False)
    op.create_index(op.f('ix_properties_price'), 'properties', ['price'], unique=False)
    op.create_index(op.f('ix_properties_rent_price'), 'properties', ['rent_price'], unique=False)
    op.create_index(op.f('ix_role_requests_id'), 'role_requests', ['id'], unique=False)
    op.drop_index('ix_user_limits_user_id', table_name='user_limits')
    op.create_index(op.f('ix_user_limits_user_id'), 'user_limits', ['user_id'], unique=True)
    op.create_index(op.f('ix_user_limits_id'), 'user_limits', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_limits_id'), table_name='user_limits')
    op.drop_index(op.f('ix_user_limits_user_id'), table_name='user_limits')
    op.create_index('ix_user_limits_user_id', 'user_limits', ['user_id'], unique=False)
    op.drop_index(op.f('ix_role_requests_id'), table_name='role_requests')
    op.drop_index(op.f('ix_properties_rent_price'), table_name='properties')
    op.drop_index(op.f('ix_properties_price'), table_name='properties')
    op.drop_index(op.f('ix_kyc_requests_id'), table_name='kyc_requests')
    op.drop_index(op.f('ix_kyc_requests_provider_reference'), table_name='kyc_requests')
    op.create_index('ix_kyc_requests_provider_reference', 'kyc_requests', ['provider_reference'], unique=False)
    op.create_unique_constraint('kyc_requests_provider_reference_key', 'kyc_requests', ['provider_reference'])
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_file_id'), table_name='documents')
    op.create_unique_constraint('uq_documents_file_id', 'documents', ['file_id'])
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_column('applications', 'background_check_consent')
    op.drop_column('applications', 'references')
    # ### end Alembic commands ###
