"""Add Application table with timestamps

Revision ID: ad12045f2cf0
Revises: dee41b99e6af
Create Date: 2025-11-21 23:58:46.150293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad12045f2cf0'
down_revision: Union[str, None] = 'dee41b99e6af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Convert status from VARCHAR to Enum with lowercase values matching ApplicationStatus model
    op.alter_column('applications', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('pending', 'approved', 'rejected', 'withdrawn', 'under_review', 'signed', 'active_lease', name='applicationstatus', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('applications', 'status',
               existing_type=sa.Enum('pending', 'approved', 'rejected', 'withdrawn', 'under_review', 'signed', 'active_lease', name='applicationstatus', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###
